---
- hosts: localhost
  become: true
  gather_facts: false

  tasks:

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Repository
        baseurl: https://pkg.jenkins.io/redhat-stable
        enabled: true
        gpgcheck: true

    - name: Install required packages
      yum:
        name:
          - java-11-openjdk
          - jenkins
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Install Docker
      yum:
        name:
          - docker
        state: present

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Grant Jenkins user sudo privileges
      lineinfile:
        path: /etc/sudoers.d/jenkins
        line: 'jenkins ALL=(ALL) NOPASSWD:ALL'
        create: true
        validate: 'visudo -cf %s'

    - name: Fetch initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Save initial admin password to file
      copy:
        content: "{{ jenkins_password.content | b64decode }}"
        dest: /home/ec2-user/Jpassword.txt
