---
- hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Update software packages
      yum:
        name: "*"
        state: latest

    - name: Add Jenkins repo
      command: "sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    
    - name: Import Jenkins key
      command: "sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"

    - name: Install Java (Amazon Linux 2)
      amazon_linux_2:
        name: java-openjdk11
        state: present

    - name: Install Jenkins and Docker
      yum:
        name: 
          - jenkins
          - yum-utils
          - docker
        state: latest

    - name: Enable and start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Add Jenkins to sudoers
      blockinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        block: "jenkins ALL=(ALL) NOPASSWD:ALL"
        create: yes

    - name: Copy Jenkins initialAdminPassword
      fetch:
        src: /var/lib/jenkins/secrets/initialAdminPassword
        dest: /home/ec2-user/Jpassword.txt
        flat: yes
        fail_on_missing: yes

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted
